name: "CI Pipeline for My App"

on:
  push:
    branches:
      - main

jobs:
  use-template:
    uses: ./.github/workflows/build-test-deploy-template.yml
    with:
      app_name: 'my-node-app'
      environment: 'production'
    secrets:
      DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
