name: Caller for build Test & deploy..
on:
  push:
    branches:
      - main
    paths:
      - 'caller.yml'            
      - '.github/workflows/caller.yml'     
      
jobs:
  use-template:
    uses: ./.github/workflows/build-test-deploy-template.yml
    with:
      environment: 'production'
      app_name: 'my-node-app'
    secrets:
      DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
