name: Legacy CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Build app
        run: npm run build

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Test app
        run: npm test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to prod
        run: echo "Deploying with ${{ secrets.DEPLOY_TOKEN }}"
