name: App Pipeline Using Template

on:
  push:
    branches:
      - main

jobs:
  main:
    uses: ./.github/workflows/build-test-deploy-template.yml
    with:
      app_name: "my-awesome-app"
      environment: "production"
    secrets:
      DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
