name: Approval to Deploy 

on:
  workflow_dispatch:  # Manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: production   # <-- Connects job to "production" environment
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: echo "Building the project..."

      - name: Deploy
        run: echo "Deploying to production!"
