name: Test Email Notification

on:
  push:
    branches:
      - main

jobs:
  check_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check Something
        run: |
          echo "Simulating your real step here.....
          # exit 0  # Pass
          # exit 1  # Fail (uncomment to test notification)

    if: failure()  # Only runs on job failure
    steps:
      - name: Send deployment failure email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "🚨 Deployment Failed: ${{ github.workflow }}"
          body: |
            The deployment workflow **${{ github.workflow }}** failed.
            Repository: **${{ github.repository }}**
            Commit: ${{ github.sha }}
            Actor: ${{ github.actor }}
            Run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

            Please review the workflow logs for more details.
          to: "target.email@example.com"
          from: "your-bot@example.com"
          secure: true
