name: Test Email Notification

on:
  push:
    branches:
      - main

jobs:
  check_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check Something
        run: |
          echo "Simulating your real step here"
          # exit 0  # Pass
          # exit 1  # Fail (uncomment to test notification)

  notify_on_failure:
    needs: check_job
    if: failure()
    uses: ./.github/workflows/send-email-notification.yml
    with:
      failed_job: "check_job"
      run_url: ${{ github.run_url }}
      sha: ${{ github.sha }}
      actor: ${{ github.actor }}
